# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ce5548fd2c7cf2e8e3b3f88de1e7affbfb57dc13442b79fd2c62bf1a88af7abf7d5a3cd87788f74ec9d7f6b464537131623f4b8e299da3611a03c075025fc19

test:
  secret_key_base: d7988095eb77807e1c799877faf7eb259957687b4acfd28aa7d7cf37f713e6d825714e3de8dec427cdb64d6168488e46e78ecbebd14c293a8d6c43260739f738

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
